name: E-Commerce Tests

on:
  schedule:
    - cron: "0 22 * * 1"
  workflow_dispatch:

jobs:
  ecommerce-tests:
    if: vars.RUN_TESTS == 'true'
    name: E-Commerce Automation
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "10.0.x"

      - run: dotnet restore "E-Commerce Automation/E-Commerce Automation.csproj"
      - run: dotnet build "E-Commerce Automation/E-Commerce Automation.csproj" --no-restore
      - run: dotnet test "E-Commerce Automation/E-Commerce Automation.csproj" --no-build --verbosity normal
